### ISSUE TITLE
Frontend - image profile in predictions

### ISSUE THREAD

**Issue by robertmurer** [robertmurer/todosalacancha#120]
If no image profile for logged in user, please show default circle image profile provided in design

default image
![profilemenu](https://user-images.githubusercontent.com/35821871/38471600-bc1b8728-3b49-11e8-9468-d2e0d27f022f.png)

to be shown in these views if user has no image
![image](https://user-images.githubusercontent.com/35821871/38471593-a3a834ca-3b49-11e8-9e43-adfd631c823d.png)

![image](https://user-images.githubusercontent.com/35821871/38471620-e8ac86ac-3b49-11e8-9334-3c9775af89ab.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
I still unable to see default image in ranking or predictions page:

company: google, user: rmurer11, pass rmurer11

http://todosalacancha.sietepuentes.com/google/pronosticos/fase
![image](https://user-images.githubusercontent.com/35821871/38516407-746024b0-3c0d-11e8-8151-1a1007ec3da6.png)

http://todosalacancha.sietepuentes.com/google/ranking
![image](https://user-images.githubusercontent.com/35821871/38516458-931a0b3c-3c0d-11e8-9b32-374376790f71.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
ok

**Comment by robertmurer** [comment]
This is broken again
