### ISSUE TITLE
Frontend - Left Menú

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#122]
the links are up, it has to be on the red background
![image](https://user-images.githubusercontent.com/34341691/38568257-9f60f462-3cbe-11e8-8b75-8d737105319e.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by carlos-segovia** [comment]
it's still wrong. 
Tested in Firefox and Chrome.
Please resize the screen to test it.

**Comment by carlos-segovia** [comment]
done!
