### ISSUE TITLE
Frontend - Pronosticos

### ISSUE THREAD

**Issue by carlos-segovia** [robertmurer/todosalacancha#131]
1) it's showing a number after the away_team_id. Please shoy only the name of the team
![image](https://user-images.githubusercontent.com/34341691/38636854-c94ae8f0-3d9f-11e8-8e59-55b2af0605eb.png)

2) insert only the prediction for one team and leave the other empty
TEST A:
a) Insert 3 goals to Argentina
![image](https://user-images.githubusercontent.com/34341691/38632427-1c2b1098-3d93-11e8-9faa-47fa47169040.png)
b) click in Pronosticar button
![image](https://user-images.githubusercontent.com/34341691/38632487-440231aa-3d93-11e8-9195-75507a081cca.png)
c) Error message with text : "Sus pronósticos no se guardaron, por favor verifique"
![image](https://user-images.githubusercontent.com/34341691/38632544-6eeaaabe-3d93-11e8-8575-6ec5fb256a1c.png) 
The message means: "predictions weren't saved , please validate". We need to add why the predictions weren't saved.
ACTION: Change the message to "Sus pronósticos no se guardaron,  verifique que insertó el pronóstico para los dos equipos."
The message must be showed in the window with the below design:
![image](https://user-images.githubusercontent.com/34341691/38637244-f09fc974-3da0-11e8-976f-9a9dcf686b67.png)

TEST B:
a) insert 5 goals to Japon
![image](https://user-images.githubusercontent.com/34341691/38637309-2759dec8-3da1-11e8-913c-e9959623fddc.png)
b) click in Pronosticar button
![image](https://user-images.githubusercontent.com/34341691/38632487-440231aa-3d93-11e8-9195-75507a081cca.png)
c)Error message with text : "Tus pronosticos fueron guardados".
The message means that predictions were saved and this is wrong becuase predictions were not saved.
![image](https://user-images.githubusercontent.com/34341691/38637355-52d69212-3da1-11e8-995a-7cdd770909ab.png)
ACTION: Change the text to "Sus pronósticos no se guardaron,  verifique que insertó el pronóstico para los dos equipos."

3) 24 hours before kickoff game
a) Show only the predictions without the imput. If the game dont have a prediction show only -
b) Show the timer not Expired
![image](https://user-images.githubusercontent.com/34341691/38638425-9957f3e0-3da4-11e8-96b5-a3469db16cfa.png)

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
I've checked and working fine @carlos-segovia please double check and close.

**Comment by carlos-segovia** [comment]
When you insert prediction to  **away_team_id** only its NOT solved.
Please see TEST B

**Comment by debasishpaul2014** [comment]
didn't get your point

**Comment by robertmurer** [comment]
Enter prediction for any match as follows:  X - 5.    Then click pronosticar.  There should appear the same error message  "Sus pronósticos no se guardaron, verifique que insertó el pronóstico para los dos equipos."

If you enter 5 - X and click "Pronosticar" it works fine

**Comment by debasishpaul2014** [comment]
done

**Comment by robertmurer** [comment]
working fine
